version: '3'

services:

  frontend:
    labels:
      shipyard.route: '/'
    build: 'frontend'
    environment:
      CI: 'true'
      DANGEROUSLY_DISABLE_HOST_CHECK: 'true'
    volumes:
      - './frontend/src:/srv/src'
    ports:
      - '3000:3000'

  backend:
    labels:
      shipyard.route: '/api'
    build: 'backend'
    volumes:
      - './backend/src:/srv/src'
    ports:
      - '3001:3001'